[[monitors]]
enabled = true
name = "MySQL"
execute_every = 10

[monitors.heartbeat]
method = "GET"
url = ""

[monitors.mysql]
url = "mysql://username:password@localhost:3306/db_name"


[[monitors]]
enabled = true
name = "PostgreSQL"
execute_every = 10

[monitors.heartbeat]
method = "GET"
url = ""

[monitors.postgresql]
url = "postgresql://username:password@localhost:5432/db_name"


[[monitors]]
enabled = true
name = "Redis"
execute_every = 10

[monitors.heartbeat]
method = "GET"
url = ""

[monitors.redis]
url = "redis://username:password@localhost:6379/db_name"

[[monitors]]
enabled = true
name = "PulseMonitor"
execute_every = 10

[monitors.heartbeat]
method = "GET"
url = ""